import JSZip from 'jszip';
import { QuizData, Question, QuestionType } from '../types';

// Helper to escape XML characters
const escapeXml = (unsafe: string) => {
  return unsafe.replace(/[<>&'"]/g, (c) => {
    switch (c) {
      case '<': return '&lt;';
      case '>': return '&gt;';
      case '&': return '&amp;';
      case '\'': return '&apos;';
      case '"': return '&quot;';
      default: return c;
    }
  });
};

// Generates the unique identifier for the manifest
const generateManifestId = () => `MANIFEST-${crypto.randomUUID()}`;

// 1. Generate imsmanifest.xml
const generateManifest = (quiz: QuizData, questionIds: string[]) => {
  const manifestId = generateManifestId();
  const resources = questionIds.map(id => `
    <resource identifier="resource_${id}" type="imsqti_item_xmlv2p1" href="items/${id}.xml">
      <file href="items/${id}.xml"/>
    </resource>
  `).join('\n');

  // Add the assessment resource
  const assessmentResourceId = `resource_assessment_${crypto.randomUUID()}`;
  const assessmentHref = "assessment/assessment.xml";

  return `<?xml version="1.0" encoding="UTF-8"?>
<manifest xmlns="http://www.imsglobal.org/xsd/imscp_v1p1"
          xmlns:imsmd="http://www.imsglobal.org/xsd/imsmd_v1p2"
          xmlns:imsqti="http://www.imsglobal.org/xsd/imsqti_v2p1"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://www.imsglobal.org/xsd/imscp_v1p1 http://www.imsglobal.org/xsd/imscp_v1p1.xsd http://www.imsglobal.org/xsd/imsmd_v1p2 http://www.imsglobal.org/xsd/imsmd_v1p2p2.xsd http://www.imsglobal.org/xsd/imsqti_v2p1 http://www.imsglobal.org/xsd/imsqti_v2p1.xsd"
          identifier="${manifestId}">
  <metadata>
    <schema>IMS Content</schema>
    <schemaversion>1.1.3</schemaversion>
    <imsmd:lom>
      <imsmd:general>
        <imsmd:title>
          <imsmd:langstring xml:lang="en">${escapeXml(quiz.title)}</imsmd:langstring>
        </imsmd:title>
        <imsmd:description>
           <imsmd:langstring xml:lang="en">${escapeXml(quiz.description || "Generated by AI QTI Tool")}</imsmd:langstring>
        </imsmd:description>
      </imsmd:general>
    </imsmd:lom>
  </metadata>
  <organizations/>
  <resources>
    <resource identifier="${assessmentResourceId}" type="imsqti_test_xmlv2p1" href="${assessmentHref}">
      <file href="${assessmentHref}"/>
      ${questionIds.map(id => `<dependency identifierref="resource_${id}"/>`).join('\n      ')}
    </resource>
    ${resources}
  </resources>
</manifest>`;
};

// 2. Generate Assessment XML (The Test definition)
const generateAssessment = (quiz: QuizData, questions: Question[]) => {
  const testId = `TEST-${crypto.randomUUID()}`;
  const partId = `PART-${crypto.randomUUID()}`;
  const sectionId = `SECTION-${crypto.randomUUID()}`;

  const assessmentItems = questions.map(q => `
        <assessmentItemRef identifier="itemref_${q.id}" href="../items/${q.id}.xml" fixed="false"/>
  `).join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>
<assessmentTest xmlns="http://www.imsglobal.org/xsd/imsqti_v2p1"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:schemaLocation="http://www.imsglobal.org/xsd/imsqti_v2p1 http://www.imsglobal.org/xsd/imsqti_v2p1.xsd"
                identifier="${testId}" title="${escapeXml(quiz.title)}">
  <testPart identifier="${partId}" navigationMode="linear" submissionMode="individual">
    <assessmentSection identifier="${sectionId}" title="Main Section" visible="true">
      ${assessmentItems}
    </assessmentSection>
  </testPart>
</assessmentTest>`;
};

// 3. Generate Item XML (Individual Questions)
const generateItem = (q: Question) => {
  const responseId = `RESPONSE_${q.id}`;
  
  // -- Multiple Choice & True/False Logic --
  if (q.type === QuestionType.MULTIPLE_CHOICE || q.type === QuestionType.TRUE_FALSE) {
    const correctAnswers = q.answers.filter(a => a.isCorrect);
    // If no correct answer found, fallback to first (should act differently but for safety)
    const validCorrectId = correctAnswers.length > 0 ? correctAnswers[0].id : q.answers[0]?.id;

    return `<?xml version="1.0" encoding="UTF-8"?>
<assessmentItem xmlns="http://www.imsglobal.org/xsd/imsqti_v2p1"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:schemaLocation="http://www.imsglobal.org/xsd/imsqti_v2p1 http://www.imsglobal.org/xsd/imsqti_v2p1.xsd"
                identifier="${q.id}" title="${escapeXml(q.text.substring(0, 50))}..." adaptive="false" timeDependent="false">
  <responseDeclaration identifier="RESPONSE" cardinality="single" baseType="identifier">
    <correctResponse>
      <value>${validCorrectId}</value>
    </correctResponse>
  </responseDeclaration>
  <outcomeDeclaration identifier="SCORE" cardinality="single" baseType="float">
    <defaultValue>
      <value>0</value>
    </defaultValue>
  </outcomeDeclaration>
  <itemBody>
    <choiceInteraction responseIdentifier="RESPONSE" shuffle="false" maxChoices="1">
      <prompt>${escapeXml(q.text)}</prompt>
      ${q.answers.map(a => `
      <simpleChoice identifier="${a.id}">${escapeXml(a.text)}</simpleChoice>
      `).join('')}
    </choiceInteraction>
  </itemBody>
</assessmentItem>`;
  }
  
  // -- Essay / Short Answer Logic (Simplified to extendedTextInteraction) --
  // Canvas treats Essay and Short Answer differently but structurally extendedTextInteraction covers open input.
  return `<?xml version="1.0" encoding="UTF-8"?>
<assessmentItem xmlns="http://www.imsglobal.org/xsd/imsqti_v2p1"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:schemaLocation="http://www.imsglobal.org/xsd/imsqti_v2p1 http://www.imsglobal.org/xsd/imsqti_v2p1.xsd"
                identifier="${q.id}" title="${escapeXml(q.text.substring(0, 50))}..." adaptive="false" timeDependent="false">
  <responseDeclaration identifier="RESPONSE" cardinality="single" baseType="string"/>
  <outcomeDeclaration identifier="SCORE" cardinality="single" baseType="float">
    <defaultValue>
      <value>0</value>
    </defaultValue>
  </outcomeDeclaration>
  <itemBody>
    <extendedTextInteraction responseIdentifier="RESPONSE">
      <prompt>${escapeXml(q.text)}</prompt>
    </extendedTextInteraction>
  </itemBody>
</assessmentItem>`;
};


export const createQtiZip = async (quiz: QuizData): Promise<Blob> => {
  const zip = new JSZip();

  // 1. Manifest
  const questionIds = quiz.questions.map(q => q.id);
  zip.file("imsmanifest.xml", generateManifest(quiz, questionIds));

  // 2. Assessment File
  zip.file("assessment/assessment.xml", generateAssessment(quiz, quiz.questions));

  // 3. Item Files
  quiz.questions.forEach(q => {
    zip.file(`items/${q.id}.xml`, generateItem(q));
  });

  return await zip.generateAsync({ type: "blob" });
};